### ISSUE TITLE
Support using star topology network

### ISSUE THREAD

**Issue by osukhoroslov** [osukhoroslov/dslab#242]
Suggested config format:

```
network:
  model: TopologyNetwork
  topology: star
  local_bandwidth: 100000
  local_latency: 0
  link_bandwidth: 1250
  link_latency: 10
```
