### ISSUE TITLE
Lookahead has worse result than HEFT

### ISSUE THREAD

**Issue by osukhoroslov** [osukhoroslov/dslab#251]
DAG: Any of `bwa-chameleon-large-*.json` from [here](https://github.com/wfcommons/makeflow-instances/tree/main/bwa/chameleon-cloud)

System: 

```
resources:
  - name: node1
    speed: 6
    cores: 8
    memory: 12000
  - name: node2
    speed: 5
    cores: 12
    memory: 24000
  - name: node3
    speed: 4
    cores: 24
    memory: 48000
  - name: node4
    speed: 2.6
    cores: 20
    memory: 40000
network:
  model: ConstantBandwidthNetwork
  bandwidth: 1250
  latency: 100
```
